"""Add total_price column to Order

Revision ID: 2a6beebc7c5e
Revises: 
Create Date: 2024-12-11 23:30:03.588408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6beebc7c5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_price')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
