"""Add shipping_address and billing_address to Order model

Revision ID: 8c287402d49f
Revises: 2a6beebc7c5e
Create Date: 2024-12-12 20:55:11.705869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c287402d49f'
down_revision = '2a6beebc7c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('billing_address', sa.String(length=255), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('billing_address')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
